### PR TITLE
Add detail panel, collect garbage button and complete graph selection dropdown

### PR DESCRIPTION
**Pull request by mzgoddard**
- Add detail panel
- Add collect garbage
- Add graph selection component events to open and close dropdown and select a given web audio context
- Highlight a web audio node when clicked with a thick border
- Clicking collect garbage or selecting a context from selection dropdown pushs an "action" object from their `render*` function created observables
- Separate debugger attach event machine from web audio event observer into its own class
- Send "action" objects from the panel context to devtools context to respond to user actions
- Send an action object to the devtools context when collect garbage is clicked
- When a collect garbage action is received by the devtools context call sendCommand with `HeapProfiler.collectGarbage`
- Modify webpack bundler configuration to depend on images listed in css files
- Display table of web audio context information for current selected context
- Display table of node and parameter information when a node in the context is highlighted by clicking on it

### CODE REVIEW

**Comment by mzgoddard** [comment]
- Added some overlooked changes to WebAudioEventObserver test, passing an instance of DebuggerAttachEventController to WebAudioEventObserver.
- Merged in main to resolve package-lock.json.

**Review by hoch — COMMENTED** [review]
Looks good, but can I test a build from the "dev-preview" branch?

**Comment by mzgoddard** [comment]
@hoch ah, sorry. I forgot about `dev-preview` branch and have pushed to it now.

I'm not sure what you mean by "but can I test a build". You should be able to build `dev-preview` or this pr.

**Comment by hoch** [comment]
Yeah, I was simply waiting for `dev-preview` branch. Thanks for creating it!

**Review by hoch — APPROVED** [review]
Just tested the dev-preview branch. Working great! LGTM

**Pull request merged**
