### PR TITLE
polish graph rendering and viewport controls

### PR DESCRIPTION
**Pull request by mzgoddard**
- Support multiple Web Audio contexts
- Render ports on nodes
- Smooth edge lines
- Draw edge lines between the ports the edge connects
- Add a loading screen until the panel's script is ready
- Add button that fits the graph to the viewport
- Zoom viewport around the mouse cursor
- Add viewport margin
- Constrain viewport panning when zoomed within the graph bounds
- Remove unused files

Multiple Web Audio Contexts

Collect web audio graph data in the devtools script for when the panel is opened and connects. On the panel the initial set of current graphs and updates is collected. One of those current graphs can be selected with the GraphSelector instance and it will passed on to the worker for layout and back to the panel for rendering. As one graph is rendered at any time, one instance of the rendering logic and state is reused with each graph, whichever one is currently selected. To the rendering logic receiving a graph for a web audio graph other than what it last displayed is the same as the previous graph destroying all of its nodes and making brand new ones.

### CODE REVIEW

**Review by hoch — APPROVED** [review]
LGTM

@mzgoddard I believe this PR contains your demo in our meeting on 8/19. Right?

**Comment by hoch** [comment]
@mzgoddard Friendly ping. If this is ready, please go ahead and merge it.

**Comment by hoch** [comment]
I tested the local build (bocoup-style branch) and it works fine. However, there's a notification bar up top ("...debugging this browser") and it won't close. Is there anything we can do?

**Comment by mzgoddard** [comment]
> @mzgoddard I believe this PR contains your demo in our meeting on 8/19. Right?

Yes. It has everything that was in that demo.

> @mzgoddard Friendly ping. If this is ready, please go ahead and merge it.

Will do.

> I tested the local build (bocoup-style branch) and it works fine. However, there's a notification bar up top ("...debugging this browser") and it won't close. Is there anything we can do?

I checked a few things. Its not obvious to me how to close it without disabling the extension. The bar has a `Cancel` and `x` close button. Both buttons when clicked, detach the extension. I checked `runtime.lastError` and it doesn't indicate why the detach is happening. Currently there is an event listener on detach that immediately reattaches. If I recall we can't remove that, it's part of how the extension gets a full graph when the tab is reloaded. As well if we did, the extension would not receive further WebAudio debugger events.

I think a quick incomplete solution would be to move `WebAudioEventObserver` and `WebAudioGraphIntegrator` from the devtools script and into the panel script. This would start the debugger when the `Web Audio` panel is opened. Which would cause that banner to appear. But only when the `Web Audio` panel is intentionally being used by the user. Maybe the panel should be renamed to `Audion` to help draw that relationship.

I think a more complete solution may be adding user settings that lets the user specify if they want it to attach to the debugger when devtools is opened or the panel is opened. And if it should reattach automatically when the panel is inactive.

As well there could be some solution in the extension manifest or api that I am unaware of.

**Pull request merged**
