### PR TITLE
Revert "Patch graph context"

### PR DESCRIPTION
**Pull request by mzgoddard**
Reverts GoogleChrome/audion#133

Fix https://github.com/GoogleChrome/audion/issues/143

#133 is a nice optimization but there is an issue and until that is fixed we can revert this.

### CODE REVIEW

**Comment by hoch** [comment]
Hmm, not sure why CLA is not working?

Also were you able to confirm reverting this fixes #143 locally?

**Review by hoch — APPROVED** [review]
LGTM. Please test this locally before merging.

**Comment by hoch** [comment]
Friendly ping - @mzgoddard. It would be great if you can test/confirm the patch locally.

**Comment by mzgoddard** [comment]
@hoch Sorry for the delay. I confirmed locally but forgot to state so here. I checked again and its still good.

**Pull request merged**
